"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[717],{7438:function(R,d,i){i.d(d,{f:function(){return t}});var E=i(82092),T=i.n(E),D=i(48305),m=i.n(D),M=i(95744),u=i(19158),j=i(34505),x=i(53595),C=i(73844),P=i(64616),g=i(32699),v=i.n(g),A=i(93236),c=i(62086),e="encryptedKey",t=function(){var s=localStorage.getItem(e);return s&&window.atob(window.atob(s))},p=function(){var s=u.Z.useForm(),b=m()(s,1),f=b[0],w=(0,A.useState)(!1),y=m()(w,2),o=y[0],n=y[1];return(0,A.useEffect)(function(){o&&f.setFieldsValue(T()({},e,localStorage.getItem(e)))},[o]),(0,c.jsxs)(c.Fragment,{children:[(0,c.jsx)(M.Z,{onClick:function(){return n(!0)}}),(0,c.jsx)(j.Z,{open:o,title:"MongoDB Altas",footer:(0,c.jsx)(x.ZP,{type:"primary",onClick:function(){return f.validateFields().then(function(r){if((0,g.isEmpty)(r[e]))j.Z.confirm({title:"\u8B66\u544A",content:"\u786E\u8BA4\u540E\u5C06\u6E05\u9664Data Api Key\u7F13\u5B58",onOk:function(){return localStorage.removeItem(e)}});else try{r[e]!==localStorage.getItem(e)&&localStorage.setItem(e,window.btoa(window.btoa(r[e]))),n(!1)}catch(_){C.ZP.error({message:"\u4FDD\u5B58\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5\u8F93\u5165\u65E0\u7279\u6B8A\u5B57\u7B26\u540E\u5C1D\u8BD5\u4FDD\u5B58"})}})},children:"\u786E\u5B9A"}),onCancel:function(){return n(!1)},children:(0,c.jsx)(u.Z,{name:"mongodb",form:f,children:(0,c.jsx)(u.Z.Item,{label:"Data Api Key",name:e,children:(0,c.jsx)(P.Z.TextArea,{rows:10,allowClear:!0})})})})]})};d.Z=p},8291:function(R,d,i){i.r(d),i.d(d,{default:function(){return w}});var E=i(48305),T=i.n(E),D=i(38880),m=i(18192),M=i(87403),u=i(80416),j=i(27802),x=i(99069),C=i(62897),P=i(64616),g=i(93236),v=i(88331),A=i(26068),c=i.n(A),e=64,t={rx:"32",ry:"32",style:{fill:"red",stroke:"black",strokeSidth:5,opacity:.5}},p=function(){return`<svg viewBox="0 0 1024 1024" width="1em" height="1em" fill="currentColor">
      <rect x="0" y="0" rx="`.concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="512" height="').concat(e,`" />
      <rect x="`).concat(512-e,'" y="0" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="').concat(e,`" height="1024" />
      <rect x="0" y="`).concat(1024-e,'" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="512" height="').concat(e,`" />
      <rect x="0" y="512" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="').concat(e,`" height="512" />
      <rect x="0" y="512" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="512" height="').concat(e,`" />
      <rect x="512" y="`).concat(512-e,'"  rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="512" height="').concat(e,`" /> 
      <rect x="`).concat(1024-e,'" y="512" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="').concat(e,`" height="246" />
      <rect x="768" y="512" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="256" height="').concat(e,`" />
      <rect x="512" y="`).concat(512-e,'" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="512" height="').concat(e,`" />
      <rect x="`).concat(1024-e,'" y="0" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="').concat(e,`" height="512" />
      <rect x="512" y="0" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="512" height="').concat(e,`" />
      <rect x="512" y="0" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="').concat(e,`" height="768" />
      <rect x="512" y="`).concat(768-e,'" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="512" height="').concat(e,`" />
      <rect x="768" y="512" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="').concat(e,`" height="512" />
      <rect x="512" y="`).concat(1024-e,'" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="256" height="').concat(e,`" />
      <rect x="512" y="768" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="').concat(e,`" height="256" />
      <rect x="512" y="768" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="512" height="').concat(e,`" />
      <rect x="`).concat(1024-e,'" y="768" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(o){var n=_slicedToArray(o,2),a=n[0],r=n[1];return"".concat(a,": ").concat(r)}).join(";"),'" width="').concat(e,`" height="256" />
    </svg>`)},l=i(62086),s=function(){return(0,l.jsxs)("svg",{viewBox:"0 0 1024 1024",width:"1em",height:"1em",fill:"currentColor",children:[(0,l.jsx)("rect",c()(c()({},t),{},{x:"0",y:"0",width:"512",height:e})),(0,l.jsx)("rect",c()(c()({},t),{},{x:512-e,y:"0",width:e,height:"1024"})),(0,l.jsx)("rect",c()(c()({},t),{},{x:"0",y:1024-e,width:"512",height:e})),(0,l.jsx)("rect",c()(c()({},t),{},{x:"0",y:"512",width:e,height:"512"})),(0,l.jsx)("rect",c()(c()({},t),{},{x:"0",y:"512",width:"512",height:e})),(0,l.jsx)("rect",c()(c()({},t),{},{x:"512",y:512-e,width:"512",height:e})),(0,l.jsx)("rect",c()(c()({},t),{},{x:1024-e,y:"0",width:e,height:"512"})),(0,l.jsx)("rect",c()(c()({},t),{},{x:"512",y:"0",width:"512",height:e})),(0,l.jsx)("rect",c()(c()({},t),{},{x:"512",y:"0",width:e,height:"768"})),(0,l.jsx)("rect",c()(c()({},t),{},{x:"512",y:768-e,width:"512",height:e})),(0,l.jsx)("rect",c()(c()({},t),{},{x:1024-e,y:"512",width:e,height:"246"})),(0,l.jsx)("rect",c()(c()({},t),{},{x:"768",y:"512",width:"256",height:e})),(0,l.jsx)("rect",c()(c()({},t),{},{x:"768",y:"512",width:e,height:"512"})),(0,l.jsx)("rect",c()(c()({},t),{},{x:"512",y:1024-e,width:"256",height:e})),(0,l.jsx)("rect",c()(c()({},t),{},{x:"512",y:"768",width:e,height:"256"})),(0,l.jsx)("rect",c()(c()({},t),{},{x:"512",y:"768",width:"512",height:e})),(0,l.jsx)("rect",c()(c()({},t),{},{x:1024-e,y:"768",width:e,height:"256"}))]})},b=s,f=i(7438);function w(){var y=(0,v.Ov)(),o=y.clientRoutes,n=(0,v.TH)(),a=(0,g.useState)(0),r=T()(a,2),_=r[0],I=r[1],B=[x.Z.defaultAlgorithm,x.Z.darkAlgorithm,x.Z.compactAlgorithm],K=[D.Z,m.Z,M.Z],Z=function(){return I((_+1)%B.length)};return(0,l.jsx)(C.ZP,{theme:{algorithm:B[_]},children:(0,l.jsx)(j.f,{layout:"mix",logo:(0,l.jsx)(u.Z,{component:function(){return(0,l.jsx)(b,{})}}),title:"JehChen",avatarProps:{src:"/Logo.svg",size:"small",title:"Jeh"},actionsRender:function(h){return h.isMobile?[]:[h.layout!=="side"&&document.body.clientWidth>1400?(0,l.jsx)(P.Z,{}):void 0,(0,l.jsx)(f.Z,{}),(0,g.createElement)(K[_],{onClick:Z})]},route:o[0],location:n,menuItemRender:function(h,L){return h.isUrl||h.children?L:h.path&&n.pathname!==h.path?(0,l.jsx)(v.rU,{to:h.path,target:h.target,children:L}):L},menuFooterRender:function(){return"@JehChen"},children:(0,l.jsx)(v.j3,{})})})}}}]);
