"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[717],{95350:function(it,E,s){s.r(E),s.d(E,{default:function(){return rt}});var L=s(48305),f=s.n(L),u=s(74296),st="https://ap-southeast-1.aws.services.cloud.mongodb.com/api/client/v2.0/app/data-erhzmlq/auth/providers/local-userpass/login",I="https://ap-southeast-1.aws.data.mongodb-api.com/app/data-erhzmlq/endpoint/data/v1/action/find",A="username",T="access_token",M=function(c){return sessionStorage.setItem(T,c)},R=function(){return sessionStorage.getItem(T)},b=function(){return sessionStorage.removeItem(T)},lt=function(c,e){sessionStorage.setItem(A,c),M(e),history.push("/")},k=function(){return sessionStorage.getItem(A)},D=function(){b(),sessionStorage.removeItem(A),u.m8.push("/"),location.reload()},F=s(84232),z=s(25682),H=s(16160),J=s(45944),j=s(60674),N=s(25606),d=s(75271),a=s(52676),G=function(){var c=(0,d.useState)(!1),e=f()(c,2),r=e[0],o=e[1],S=(0,d.useState)([]),v=f()(S,2),g=v[0],O=v[1],Z=function(){N.Z.post(I,{collection:"users",database:"sample_mflix",dataSource:"JehChenxx"},{headers:{Authorization:"Bearer ".concat(R())}}).then(function(x){var C=x.data;return O(C.documents)}).catch(function(){return F.ZP.error({message:"\u67E5\u8BE2\u5931\u8D25"})})};return(0,d.useEffect)(function(){Z()},[r]),(0,a.jsxs)(a.Fragment,{children:[(0,a.jsx)(z.ZP,{onClick:function(){return o(!0)},children:"\u6570\u636E\u5E93\u793A\u4F8B\u6570\u636E"}),(0,a.jsx)(H.Z,{width:"80vw",open:r,onCancel:function(){return o(!1)},title:"\u6570\u636E\u5E93\u793A\u4F8B\u6570\u636E",footer:null,children:(0,a.jsxs)(J.Z,{rowKey:"_id",dataSource:g,children:[(0,a.jsx)(j.Z,{title:"_id",dataIndex:"_id"},"_id"),(0,a.jsx)(j.Z,{title:"Name",dataIndex:"name"},"name"),(0,a.jsx)(j.Z,{title:"email",dataIndex:"email"},"email"),(0,a.jsx)(j.Z,{title:"password",dataIndex:"password"},"password")]})})]})},K=G,V=s(19317),W=s(18455),Y=s(52081),P=s(85223),Q=s(90879),X=s(23270),$=s(2596),w=s(34753),q=s(6280),_=s(68067),U=s(26793),tt=s(35344),et=s(26068),i=s.n(et),n=64,t={rx:"32",ry:"32",style:{fill:"red",stroke:"black",strokeSidth:5,opacity:.5}},ht=function(){return`<svg viewBox="0 0 1024 1024" width="1em" height="1em" fill="currentColor">
      <rect x="0" y="0" rx="`.concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="512" height="').concat(n,`" />
      <rect x="`).concat(512-n,'" y="0" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="').concat(n,`" height="1024" />
      <rect x="0" y="`).concat(1024-n,'" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="512" height="').concat(n,`" />
      <rect x="0" y="512" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="').concat(n,`" height="512" />
      <rect x="0" y="512" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="512" height="').concat(n,`" />
      <rect x="512" y="`).concat(512-n,'"  rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="512" height="').concat(n,`" /> 
      <rect x="`).concat(1024-n,'" y="512" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="').concat(n,`" height="246" />
      <rect x="768" y="512" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="256" height="').concat(n,`" />
      <rect x="512" y="`).concat(512-n,'" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="512" height="').concat(n,`" />
      <rect x="`).concat(1024-n,'" y="0" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="').concat(n,`" height="512" />
      <rect x="512" y="0" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="512" height="').concat(n,`" />
      <rect x="512" y="0" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="').concat(n,`" height="768" />
      <rect x="512" y="`).concat(768-n,'" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="512" height="').concat(n,`" />
      <rect x="768" y="512" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="').concat(n,`" height="512" />
      <rect x="512" y="`).concat(1024-n,'" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="256" height="').concat(n,`" />
      <rect x="512" y="768" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="').concat(n,`" height="256" />
      <rect x="512" y="768" rx="`).concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="512" height="').concat(n,`" />
      <rect x="`).concat(1024-n,'" y="768" rx="').concat(t.rx,'" ry="').concat(t.ry,'" style="').concat(Object.entries(t.style).map(function(c){var e=_slicedToArray(c,2),r=e[0],o=e[1];return"".concat(r,": ").concat(o)}).join(";"),'" width="').concat(n,`" height="256" />
    </svg>`)},nt=function(){return(0,a.jsxs)("svg",{viewBox:"0 0 1024 1024",width:"1em",height:"1em",fill:"currentColor",children:[(0,a.jsx)("rect",i()(i()({},t),{},{x:"0",y:"0",width:"512",height:n})),(0,a.jsx)("rect",i()(i()({},t),{},{x:512-n,y:"0",width:n,height:"1024"})),(0,a.jsx)("rect",i()(i()({},t),{},{x:"0",y:1024-n,width:"512",height:n})),(0,a.jsx)("rect",i()(i()({},t),{},{x:"0",y:"512",width:n,height:"512"})),(0,a.jsx)("rect",i()(i()({},t),{},{x:"0",y:"512",width:"512",height:n})),(0,a.jsx)("rect",i()(i()({},t),{},{x:"512",y:512-n,width:"512",height:n})),(0,a.jsx)("rect",i()(i()({},t),{},{x:1024-n,y:"0",width:n,height:"512"})),(0,a.jsx)("rect",i()(i()({},t),{},{x:"512",y:"0",width:"512",height:n})),(0,a.jsx)("rect",i()(i()({},t),{},{x:"512",y:"0",width:n,height:"768"})),(0,a.jsx)("rect",i()(i()({},t),{},{x:"512",y:768-n,width:"512",height:n})),(0,a.jsx)("rect",i()(i()({},t),{},{x:1024-n,y:"512",width:n,height:"246"})),(0,a.jsx)("rect",i()(i()({},t),{},{x:"768",y:"512",width:"256",height:n})),(0,a.jsx)("rect",i()(i()({},t),{},{x:"768",y:"512",width:n,height:"512"})),(0,a.jsx)("rect",i()(i()({},t),{},{x:"512",y:1024-n,width:"256",height:n})),(0,a.jsx)("rect",i()(i()({},t),{},{x:"512",y:"768",width:n,height:"256"})),(0,a.jsx)("rect",i()(i()({},t),{},{x:"512",y:"768",width:"512",height:n})),(0,a.jsx)("rect",i()(i()({},t),{},{x:1024-n,y:"768",width:n,height:"256"}))]})},ct=nt;function rt(){var l=(0,u.Ov)(),c=l.clientRoutes,e=(0,u.YB)(),r=e.formatMessage,o=(0,u.TH)(),S=(0,d.useState)(0),v=f()(S,2),g=v[0],O=v[1],Z=(0,d.useState)(),m=f()(Z,2),x=m[0],C=m[1];(0,d.useEffect)(function(){var y=k();(0,tt.isNil)(y)||C(y)},[k()]);var B=[w.Z.defaultAlgorithm,w.Z.darkAlgorithm,w.Z.compactAlgorithm],at=[V.Z,W.Z,Y.Z],ot=function(){return O((g+1)%B.length)};return(0,a.jsx)(q.ZP,{theme:{algorithm:B[g]},children:(0,a.jsx)($.ZP,{layout:"mix",logo:(0,a.jsx)(P.Z,{component:function(){return(0,a.jsx)(ct,{})}}),title:"JehChenxx",onMenuHeaderClick:function(){return u.m8.push("/")},avatarProps:{src:"/Logo.svg",size:"small",title:x},actionsRender:function(h){return h.isMobile?[]:[h.layout!=="side"&&document.body.clientWidth>1400?x&&(0,a.jsxs)(a.Fragment,{children:[r({id:"user.welcome"},{name:x}),(0,a.jsx)(K,{})]}):void 0,x?(0,a.jsx)(_.Z,{title:r({id:"app.logout.confirm"}),onConfirm:D,children:(0,a.jsx)(U.Z,{title:r({id:"app.logout."}),children:(0,a.jsx)(Q.Z,{})})}):(0,a.jsx)(U.Z,{title:r({id:"app.login"}),children:(0,a.jsx)(X.Z,{onClick:function(){return u.m8.push("/login")}})}),(0,d.createElement)(at[g],{onClick:ot})]},route:c[0],location:o,menuItemRender:function(h,p){return h.isUrl||h.children?p:h.path&&o.pathname!==h.path?(0,a.jsx)(u.rU,{to:h.path,target:h.target,children:p}):p},menuFooterRender:function(){return"@JehChen"},children:(0,a.jsx)(u.j3,{})})})}}}]);
